name: Deploy MkDocs site to GitHub Pages (using git commands)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and required theme
        run: pip install mkdocs mkdocs-dracula-theme

      - name: Build MkDocs site
        run: mkdocs build --config-file docs/mkdocs.yml --site-dir site

      - name: Deploy to GitHub Pages
        run: |
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --set-upstream origin gh-pages:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}