name: site deployment

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and required theme
        run: pip install mkdocs mkdocs-material mkdocs-glightbox

      # - name: Copy files
      #   run: cp README.md site_docs/docs/index.md

      - name: Deploy to GitHub Pages using mkdocs gh-deploy
        run: |
          mkdocs gh-deploy --config-file site_docs/mkdocs.yml --remote-branch gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}