name: Python Tests

on:
  push:
    branches:
      - main  # Or your default branch name
  pull_request:
    branches:
      - main  # Or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest  # Or another operating system

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Install pytest

    - name: copy music files in 'assets/music'
      run: |
        
    - name: Run tests with pytest
      run: |
        pytest tests/  # Run all tests in the 'tests' directory