name: Python Tests

on:
  push:
    branches:
      - main  # Or your default branch name
  pull_request:
    branches:
      - main  # Or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pygame
        
    - name: Run tests with pytest
      run: |
        pytest TESTS/  # Run all tests in the 'tests' directory